import {
  app,
  BrowserWindow,
  ipcMain,
  Menu,
  nativeImage,
  net,
  protocol,
  Tray,
} from "electron";
import ffmpeg from "fluent-ffmpeg";

import path from "path";
import { initIPCEvents } from "./lib/ipcEvents";
import { downloadProcessorCron, Scheduler } from "./lib/scheduler";
import { initGlobalSettings } from "./lib/initGlobalSettings";
import dockMenu from "./menus/dockMenu";
import { execSync } from "child_process";
import { PrismaDBFullPath } from "./lib/prisma";
import { initProtocols } from "./lib/protocols";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

export let GlobalMainWindow: BrowserWindow | null = null;
export let GlobalSchedulerInstance: InstanceType<typeof Scheduler> | null =
  null;
// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    title: "Download manager",
    width: 1440,
    height: 768,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      // enable for worker multithreading => https://www.electronjs.org/docs/latest/tutorial/multithreading
      // nodeIntegrationInWorker: true,
    },
    titleBarStyle: "hidden",
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  GlobalMainWindow = mainWindow;
  GlobalSchedulerInstance = new Scheduler(
    downloadProcessorCron(GlobalMainWindow),
  );
  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", async () => {
  initProtocols();
  initPrisma();
  initTray();
  initDock();
  initIPCEvents();
  createWindow();
  initGlobalSettings();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

const initTray = () => {
  const icon = nativeImage.createFromDataURL(
    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAARdJREFUOE+lkjtKBUEQRc8VQw1ExMBfIC7ABbzATExFlyCGrkRM5e3AxEQMTTR2BQriD0TBQMzEkivV4JuZfgxYSUH37XPr0+Kfoa73ETEJzAPOji/gRZLzSNQAC8AJsJTqR2BXknMvwApw2QAMJN31BdjZAIMc94ABzvUKImIGmAZKC4upfgZ2ALfwIem9UEZmEBHrwBGwBsw1hvgK3AAHkq47AT6MiC3gGCjuRfsE7Es6+9tDbQubCVlO8UM+Pu81xKzEkCFgkz1JrcfWdVZQXCJiwxpJF03n2hBngSmPIgXfmScy2/BT0lsLEBG+PAS28+t2mfprn+Ymfk2aaxwAq0BxbkJcyS1wJakNqPU57nzsEPsAfwCE71IRtv4GYwAAAABJRU5ErkJggg==",
  );
  const tray = new Tray(icon);
  tray.setToolTip("Electron Download Manager");
  tray.setContextMenu(dockMenu);
};

const initDock = () => {
  const icon = nativeImage.createFromPath("src/images/icons/dock.png");
  app.dock.setMenu(dockMenu);
  app.dock.setIcon(icon);
};

const initPrisma = () => {
  try {
    execSync(
      `export DATABASE_URL="${PrismaDBFullPath}" && npx prisma migrate deploy`,
      { stdio: "inherit" },
    );
  } catch (error: any) {
    console.log("exec error:: ", error?.message);
  }
};

//Register the protocol
protocol.registerSchemesAsPrivileged([
  {
    scheme: "media",
    privileges: {
      secure: true,
      supportFetchAPI: true,
      bypassCSP: true,
      stream: true,
    },
  },
]);
